import { DM_Sans } from 'next/font/google'
import "@/styles/style.scss"
import AppsLayout from '@/layout/apps-layout/AppsLayout';

// Font Family
const dm_sans = DM_Sans({
  weight: ["400", "500", "700"],
  display: "swap",
  subsets: ["latin"],
  variable: '--font-pd'
})

export const metadata = {
  title: "Demo Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dm_sans.variable} bg-light`}>
        <AppsLayout>
          {children}
        </AppsLayout>
      </body>
    </html>
  );
}
